name: Integration tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ubuntu 24 test
        uses: docker://quay.io/podman/stable
        with:
          args: integration/jobs/test-on-ubuntu-24
      - name: Fedora test
        uses: docker://quay.io/podman/stable
        with:
          args: integration/jobs/test-on-fedora
      - name: Debian 12 test
        uses: docker://quay.io/podman/stable
        with:
          args: integration/jobs/test-on-debian-12
      - name: CentOS 9 test
        uses: docker://quay.io/podman/stable
        with:
          args: integration/jobs/test-on-centos-9
